insert into Publisher (id, name) values (default, 'Feeney, Ortiz and Howell');
insert into Publisher (id, name) values (default, 'Spinka, Altenwerth and Stiedemann');
insert into Publisher (id, name) values (default, 'Homenick Inc');
insert into Publisher (id, name) values (default, 'Stokes, Kuhic and Schamberger');
insert into Publisher (id, name) values (default, 'Maggio, Haag and Kuhic');
insert into Publisher (id, name) values (default, 'Ondricka-Hickle');
insert into Publisher (id, name) values (default, 'Dach Group');
insert into Publisher (id, name) values (default, 'Boyer, Robel and Simonis');
insert into Publisher (id, name) values (default, 'Langworth-Williamson');
insert into Publisher (id, name) values (default, 'Schmeler, Fritsch and Shields');
insert into Publisher (id, name) values (default, 'Pacocha, Abshire and Kovacek');
insert into Publisher (id, name) values (default, 'Ryan and Sons');
insert into Publisher (id, name) values (default, 'Oberbrunner LLC');
insert into Publisher (id, name) values (default, 'Parisian and Sons');
insert into Publisher (id, name) values (default, 'Trantow, Keeling and Braun');
insert into Publisher (id, name) values (default, 'Bartell-Lakin');
insert into Publisher (id, name) values (default, 'Stracke, Upton and Brakus');
insert into Publisher (id, name) values (default, 'Douglas, Fadel and Batz');
insert into Publisher (id, name) values (default, 'Langosh, Pouros and Shanahan');
insert into Publisher (id, name) values (default, 'Keebler, Cronin and Orn');