insert into Category (id, name) values (default, 'Action');
insert into Category (id, name) values (default, 'Crime');
insert into Category (id, name) values (default, 'Poetry');
insert into Category (id, name) values (default, '');
insert into Category (id, name) values (default, 'Science Fiction');
insert into Category (id, name) values (default, 'Comic');
insert into Category (id, name) values (default, 'Action');
insert into Category (id, name) values (default, 'Short Stories');
insert into Category (id, name) values (default, 'Memoir');
insert into Category (id, name) values (default, 'Memoir');
insert into Category (id, name) values (default, 'Romance');
insert into Category (id, name) values (default, 'Action');
insert into Category (id, name) values (default, 'Crime');
insert into Category (id, name) values (default, 'Science Fiction');
insert into Category (id, name) values (default, 'Self-Help');
insert into Category (id, name) values (default, 'Mystery');
insert into Category (id, name) values (default, 'Essays');
insert into Category (id, name) values (default, 'Science');
insert into Category (id, name) values (default, 'Memoir');
insert into Category (id, name) values (default, 'Fantasy');