insert into Category (id, name) values (default, 'Hành động');
insert into Category (id, name) values (default, 'Tội phạm');
insert into Category (id, name) values (default, 'Thơ');
insert into Category (id, name) values (default, 'Truyện tranh');
insert into Category (id, name) values (default, 'Khoc học viễn tưởng');
insert into Category (id, name) values (default, 'Truyện ngắn');
insert into Category (id, name) values (default, 'Hồi ký');
insert into Category (id, name) values (default, 'Ngôn tình');
insert into Category (id, name) values (default, 'Self-Help');
insert into Category (id, name) values (default, 'Thần loại');
insert into Category (id, name) values (default, 'Luận văn');
insert into Category (id, name) values (default, 'Kì ảo');
insert into Category (id, name) values (default, 'Lịch sử');
insert into Category (id, name) values (default, 'Chính trị');
insert into Category (id, name) values (default, 'Pháp luật');
insert into Category (id, name) values (default, 'Tôn giáo');